"""Init

Revision ID: 54e4361573ed
Revises: 
Create Date: 2019-12-31 23:47:16.611787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54e4361573ed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=256), nullable=True),
        sa.Column("menu", sa.String(length=256), nullable=True),
        sa.Column("search_id", sa.String(length=256), nullable=True),
        sa.Column("search_display", sa.String(length=256), nullable=True),
        sa.Column("search_additional", sa.String(length=256), nullable=True),
        sa.Column("subscription_time", sa.String(length=256), nullable=True),
        sa.Column("subscription_days", sa.String(length=256), nullable=True),
        sa.Column("subscription_id", sa.String(length=256), nullable=True),
        sa.Column("show_location", sa.Boolean(), nullable=True),
        sa.Column("show_groups", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
